# Generated by Django 4.2.11 on 2024-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
    ]
